import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Cookie from "./api/cookie";
import Image from "next/image";
import { Box, Card, Container, Grid, Paper, Typography } from "@mui/material";
import AddCircleOutlineIcon from "@mui/icons-material/AddCircleOutline";

export default function Home() {
  const router = useRouter();
  const [token, setToken] = useState<string>("");

  useEffect(() => {
    const accessToken = Cookie.getCookie("accessToken");
    if (accessToken) setToken(accessToken);
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </>
  );
}
